# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "centos64"

  config.hostmanager.enabled = false
  config.hostmanager.manage_host = false
  config.hostmanager.ignore_private_ip = false
  config.hostmanager.include_offline = false 

  nets = ["192.168.11", "192.168.22", "172.16.33", "172.16.44"]

  nodes = [
    "puppet",
    "control",
    "storage",
    "network",
    "compute",
    "swiftstore1",
    "swiftstore2",
    "swiftstore3",
    "tempest",
  ]

  nodes.each_index do |i|
    name = nodes[i]
    ipaddr = i + 3

    config.vm.define name do |node|
      nets.each do |net|
        node.vm.network :private_network, ip: "#{net}.#{ipaddr}"
      end

      puppet.vm.hostname = name

    puppet.vm.synced_folder "../../", "/openstack"

    puppet.vm.provider "libvirt" do |v|
      v.memory = 2048
      v.nested = true  # Do we actually want this?
    end
  end

end
