Vagrant.configure("2") do |config|
 config.vm.box = "centos64" 
 
 config.vm.define :test1 do |test1|
    test1.vm.network :private_network, :ip => "10.20.30.40"
  end

 config.vm.define :test2 do |test2|
    test2.vm.network :private_network, :ip => "10.20.30.41"
  end

end